### ISSUE TITLE
Fatal error when activating plugin

### ISSUE THREAD

**Issue by zkingdesign** [warfare-plugins/social-warfare#677]
```
Fatal error: Uncaught Error: Call to undefined method stdClass::is_home() in /Users/username/Code/siteName/wp-includes/query.php:439 Stack trace: 
#0 /Users/username/Code/siteName/wp-content/plugins/leadpages/App/Bootstrap/FrontBootstrap.php(92): is_home() 
#1 /Users/username/Code/siteName/wp-includes/class-wp-hook.php(288): LeadpagesWP\Bootstrap\FrontBootstrap->displayLeadpage(Array) 
#2 /Users/username/Code/siteName/wp-includes/plugin.php(244): WP_Hook->apply_filters(Array, Array) 
#3 /Users/username/Code/siteName/wp-includes/class-wp-query.php(2982): apply_filters_ref_array('the_posts', Array) 
#4 /Users/username/Code/siteName/wp-includes/class-wp-query.php(3230): WP_Query->get_posts() 
#5 /Users/username/Code/siteName/wp-includes/post.php(1763): WP_Query->query(Array) 
#6 /Users/username/Code/siteName/wp-content/plugins/social-warfare/lib/utilities/SWP_Database_Migration.php(223): get_posts(Array) 
#7 /Users/username/Code/siteName/wp-content/plugins/social-warfare/lib/utilities/SWP_Database_Migration.php(64) in /Users/username/Code/siteName/wp-includes/query.php on line 439
```

Receiving this error when activating the latest version of social warfare pro 3.4.

**Comment by ckmahoney** [comment]
Hello @zkingdesign ,

Please follow the directions here for plugin support: 
[Guidelines for Submitting Issues](https://github.com/warfare-plugins/social-warfare#guidelines-for-submitting-issues-to-this-github-issue-tracker)
